### ISSUE TITLE
Why do I need to provide the userId by default to create a session?

### ISSUE THREAD

**Issue by StringKe** [panates/redisess#9]
If there is an event page design, the user can pre-login to participate in the event this time you need to store some data in the session (saved in a cookie is not safe)

maybe the session should be free by default (anonymous , not associated with any user)

I'm trying to give the `create` method a default value of `anonymous `, and later in the business logic I reset the userId, will this have any effect?

**Comment by StringKe** [comment]
https://github.com/panates/redisess/blob/master/src/Session.ts#L24

**Comment by erayhanoglu** [comment]
Because the library stores session data in Redis per user, a unique user ID is required to create a new Session. I suggest you not to create sessions for anonymous users. Stateless design (cookies, local store etc) is better for the scenario that you mentioned. Otherwise you can get an attack that consuming your server memory.
